<header class="header">
  <div class="header__logo">
    <a href="/BelleEpoque/" class="logo">Belle Époque</a>
  </div>
  <nav class="header__menu">
     <ul class="header__menu--list" id="modalBurger">
      <li class="header__menu--items">
        <a href="/BelleEpoque/">Accueil</a>
      </li>
      <li class="header__menu--items">
      	 <a href="/BelleEpoque/admin">Dashboard</a>
      </li>
      <li class="header__menu--items">
      	<a href="/BelleEpoque/admin/allcours">Les cours</a>
      </li>
      <li class="header__menu--items">

        <a href="/BelleEpoque/admin/galerie">Galerie photo</a>
      </li>
    </ul>
    <div class="burger" id="openBurger">
      <span></span>
    </div>
  </nav>
</header>
