<nav class="nav-letter">
  <h3>Trouver un cours par la première lettre</h3>
  <ul class="nav-letter-ul">
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/A">A</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/B">B</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/C">C</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/D">D</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/E">E</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/F">F</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/G">H</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/I">I</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/J">J</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/K">K</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/L">L</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/M">M</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/N">N</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/O">O</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/P">P</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/Q">Q</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/R">R</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/S">S</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/T">T</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/U">U</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/V">V</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/W">W</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/X">X</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/Y">Y</a></li>
    <li class="nav-letter-li"><a href="/BelleEpoque/admin/ordercours/Z">Z</a></li>
  </ul>
</nav>
