<header class="header">
  <div class="header__logo">
    <p class="logo">Belle Époque</p>
  </div>
  <div class="header__menu">
    <ul class="header__menu--list">
      <li class="header__menu--items">
        <a href="/BelleEpoque/admin">Accueil</a>
      </li>
      <li class="header__menu--items">
        <a href="/BelleEpoque/admin/addcours">Gérer les cours</a>
      </li>
    </ul>
  </div>
</header>