<aside>
  <h3>Retrouvez nous sur Facebook!</h3>
  <div class="fb-page" data-href="https://www.facebook.com/Test-101824145997812/" 
  data-tabs="timeline" data-width="" data-height="200" data-small-header="false" 
  data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
  <blockquote cite="https://www.facebook.com/Test-101824145997812/" 
  class="fb-xfbml-parse-ignore">
  <a href="https://www.facebook.com/Test-101824145997812/">Test</a>
  </blockquote></div>
  <footer>
    
  </footer>
</aside>