<footer class="footer">
  <header class="footer__header">
    <h2>Retrouvez nous sur les réseaux</h2>
  </header>
  <main class="footer__main">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos quae 
    consectetur ad alias sunt deserunt minima enim repellendus cum eius!</p>
    <div class="main--socials">
      <i class="fa-brands fa-facebook"></i>
      <i class="fa fa-bars"></i>
      <i class="fa fa-bars"></i>
    </div>
  </main>
</footer>