<header class="header">
  <div class="header__logo">
    <a href="/BelleEpoque/"class="logo">Belle Époque</a>
  </div>
  <div class="openMenu"><i class="fa fa-bars"></i></div>
  <div class="header__menu">
    <ul class="header__menu--list">
      <li class="header__menu--items">
        <a href="/BelleEpoque/">Accueil</a>
      </li>
      <li class="header__menu--items">
        <a href="/BelleEpoque/association">L'Association</a>
      </li>
      <li class="header__menu--items">
        <a href="/BelleEpoque/allcours">Les cours</a>
      </li>
      <li class="header__menu--items">
        <a href="/BelleEpoque/galerie">Galerie photo</a>
      </li>
      <li class="header__menu--items">
        <a href="/BelleEpoque/contact">Contact</a>
      </li>
      <li class="header__menu--items">
        <a href="/BelleEpoque/legals">A Propos</a>
      </li>
    </ul>
  </div>
</header>
