<header class="header">
  <div class="header__logo">
    <a href="/BelleEpoque/"class="logo">Belle Époque</a>
  </div>
  <div class="header__menu">
    <ul class="header__menu--list">
      <li class="header__menu--items">
        <a href="/BelleEpoque/">Accueil</a>
      </li>
      <li class="header__menu--items">
        <a href="/BelleEpoque/allcours">Cours</a>
      </li>
      <li class="header__menu--items">
        <a href="/BelleEpoque/">A Propos</a>
      </li>
    </ul>
  </div>
</header>
