<?php
  foreach($lastCours as $cours)
  {
?>
<div class="cards">
  <div class="cards-top">
    <h3><?= $cours['musique'];?></h3>
  </div>
  <div class="cards-center">
    <ul class="card-information-cour">
      <li class="description-cours-li">Compte: <?= $cours['compte'];?></li>
      <li class="description-cours-li">Mur: <?= $cours['mur'];?></li>
      <li class="description-cours-li">Niveau: <?= $cours['niveau'];?></li>
      <li class="description-cours-li">Chorégraphe: <?= $cours['choregraphe'];?></li>
      <li class="description-cours-li">Musique: <?= $cours['musique'];?></li>
    </ul>
  </div>
  <div class="cards-bottom">
    <button class="button-4" role="button">
      <span class="text" >
        <a href="/BelleEpoque/singlecours/<?= $cours['id'] ?>">Voir le cours</a>
      </span>
    </button>
  </div>
</div>
<?php
  }
?>        
