
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="css/style.css" type="text/css" />
    <title>Belle-Epoque ~ </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cherry+Swash:wght@400;700&family=Montserrat&display=swap" rel="stylesheet">
</head>
<body>
      
  <main class="adm__container">
     <section class="adm__container__section--first">
        <div class="adm__section__first--masque">
              <h1>Erreur!</h1>
              <p>Requête non aboutie..</p>
        </div>
     </section>
  </main>
</body>
</html>