<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/BelleEpoque/css/style.css" type="text/css" />
    <title>Belle-Epoque ~ Erreur </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cherry+Swash:wght@400;700&family=Montserrat&display=swap" rel="stylesheet">
  </head>
  <body>
    <main class="container" id="index">
      <section class="section--first">
        <div class="first--masque">
          <h1>Erreur!</h1>
          <p>Requête non aboutie..</p>
          <button class="button-4" role="button">
          <span class="text">
          <a href="javascript:history.go(-1)">Retour</a>
          </span>
          </button>
        </div>
      </section>
    </main>
  </body>
</html>