<main class="container" id="index">
  <section class="section--second">
    <h2>Tous les cours</h2>
    <?php
      include './src/includes/_navletter.phtml';
    ?>
    <label for="search">Rechercher un cours par son titre : </label>
		<input type="text" id="search">
    <section class="section__cards" id="target">
      <?php
        foreach($allCours as $cours)
        {
      ?>
      <article class="cards">
        <div class="cards__top">
          <h3><?= $cours['title'];?></h3>
        </div>
        <div class="cards__center">
          <ul class="cards__ul">
            <li class="cards__li"><span>Compte: </span>
            <span class="li__result"><?= $cours['compte'];?></li>
            <li class="cards__li"><span>Mur: </span>
            <span class="li__result"><?= $cours['mur'];?></span></li>
            <li class="cards__li"><span>Niveau: </span>
            <span class="li__result"><?= $cours['name'];?></li>
            <li class="cards__li"><span>Chorégraphe: </span>
            <span class="li__result"><?= $cours['choregraphe'];?></span></li>
            <li class="cards__li"><span>Musique: </span>
            <span class="li__result"><?= $cours['musique'];?></span></li>
          </ul>
        </div>
        <div class="cards__bottom">
          <button class="button-4" role="button">
              <span class="text">
              <a href="/BelleEpoque/singlecours/<?= $cours['id'] ?>">Voir le cours</a>
              </span>
          </button>
        </div>
      </article>
      <?php
        }
      ?>
    </section>
    <?php require './src/includes/_navpages.phtml'; ?>
    <?php require './src/includes/_navsection.phtml'; ?>
  </section>
</main>