<main class="container" id="allcours">
  <section class="container__section--second">
    <h2>Tous les cours</h2>
    <?php
      include './src/includes/_navletter.phtml';
    ?>
    <div class="section__second--card-container">
      <?php
        foreach($allCours as $cours)
        {
      ?>
      <div class="cards">
        <div class="cards-top">
          <h3><?= $cours['title'];?></h3>
        </div>
        <div class="cards-center">
          <ul class="description-cours-ul">
            <li class="description-cours-li">Compte: <?= $cours['compte'];?></li>
            <li class="description-cours-li">Mur: <?= $cours['mur'];?></li>
            <li class="description-cours-li">Niveau: <?= $cours['niveau'];?></li>
            <li class="description-cours-li">Chorégraphe: <?= $cours['choregraphe'];?></li>
            <li class="description-cours-li">Musique: <?= $cours['musique'];?></li>
          </ul>
        </div>
        <div class="cards-bottom">
          <button class="button-4" role="button">
              <span class="text">
              <a href="/BelleEpoque/singlecours/<?= $cours['id'] ?>">Voir le cours</a> 
              </span>
          </button>
        </div>
      </div>
      <?php
        }
      ?>        
    </div>
  </section>
</main>