<main class="container" id="aside">
  <section class="section--second">
    <h2>L'association Belle Epoque c'est...</h2>
    <article class="section__cards">
      <article class="cards">
        <div class="cards--img">
        </div
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        Minima, provident, cum, facilis, fugiat similique aliquid at
        ab rerum asperiores eaque aliquam velit modi inventore enim
        delectus atque officiis voluptatibus dolore assumenda ratione
        saepe expedita quos cupiditate veniam voluptates suscipit
        molestias nulla! Officia, quas, vero, fugit accusamus asperiores
        quod ea repellendus inventore at animi cum non alias dolor
        cumque vitae culpa voluptate? Fuga, harum, maiores optio odio
        quis dolores excepturi laudantium expedita rem perspiciatis non
        atque dolor earum magni ea? Voluptatum, reprehenderit, facilis
        nihil architecto labore ipsam nulla. Impedit, debitis modi nulla
        magnam blanditiis sunt consectetur ea a quam possimus. Suscipit.</p>
      </article>
    </article>
    <h2>Lorem ipsum dolor sit amet, consectetur.</h2>
    <article class="section__cards">
      <article class="cards">
        <div class="cards--img img--second">
        </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          Debitis, beatae, tenetur, esse omnis accusantium libero
          deleniti aperiam repellendus ab nam accusamus pariatur! In,
          labore, aliquam, autem eos distinctio blanditiis repellat
          exercitationem unde perspiciatis voluptate molestias earum
          iure fugit illum nihil sint error! Porro molestiae voluptatem
          ipsam quo facere excepturi hic!</p>
      </article>
    </article>
   <?php require './src/includes/_navsection.phtml'; ?>
  </section>
  <?php require './src/includes/_aside.phtml'; ?>
</main>