<!--

Ce formulaire utilise la fonction mail() de php qui n'est pas supportée par l'IDE

-->

<main class="container" id="aside">
  <section class="section--second">
    <h2>Contactez-nous!</h2>
    <article class="section__cards">
      <article class="cards">
        <div class="cards-center">
          <form action="/BelleEpoque/contact" method="post">
               <fieldset>
                  <div class="field">
                     <label for="text">Nom & prénom</label>
                     <div class="value">
                        <input type="text" name="text">
                     </div>
                  </div>
                  <div class="field">
                     <label for="email">Email</label>
                     <div class="value">
                        <input type="email" name="email">
                     </div>
                  </div>
                  <div class="field">
                     <label for="message">Votre message</label>
                     <div class="value">
                      <textarea name="message" id="query" required ></textarea>
                     </div>
                  </div>
               </fieldset>
               <div class="toolbar">
                  <button class="button-4" type="submit">Envoyer le mail</button>
               </div>
            </form>
        </div>
      </article>
    </article>
    <?php require './src/includes/_navsection.phtml'; ?>
  </section>
  <?php require './src/includes/_aside.phtml'; ?>
</main>