<?php
  require './src/Templates/layout.phtml';
  ?>
<main class="container" id="index">
  <section class="container__section--first">
    <div class="section__first--masque">
      <h1>Belle Époque</h1>
      <p>Association de dance Country & Line</p>
    </div>
  </section>
  <section class="container__section--second">
    <h2>Derniers cours mis en ligne</h2>
    <div class="section__second--card-container">
      <?php 
        require './src/Templates/lastcours.phtml';
      ?>
    </div>
    <div class="section__second--all">
      <button>
      <a href="#">Tout les cours</a>
      </button>
    </div>
  </section>
  <!--Section Calendrier commentée a retravailler-->
  <!-- <section class="container__section--third">-->
  <!--    <h2>Date à retenir</h2>-->
  <!--    <div id="container">-->
  <!--        <div id="header">-->
  <!--            <div id="monthDisplay"></div>-->
  <!--            <div>-->
  <!--                <button id="backButton">Précédent</button>-->
  <!--                <button id="nextButton">Suivant</button>-->
  <!--            </div>-->
  <!--        </div>-->
  <!--        <div id="weekdays">-->
  <!--            <div>Dimanche</div>-->
  <!--            <div>Lundi</div>-->
  <!--            <div>Mardi</div>-->
  <!--            <div>Mercredi</div>-->
  <!--            <div>Jeudi</div>-->
  <!--            <div>Vendredi</div>-->
  <!--            <div>Samedi</div>-->
  <!--        </div>-->
  <!--        <div id="calendar"></div>-->
  <!--    </div>-->
  <!--    <div id="newEventModal">-->
  <!--        <h3>Nouvel évenement</h3>-->
  <!--        <input id="eventTitleInput" placeholder="Titre de l'évenement">-->
  <!--        <button id="saveButton">Enregistrer</button>-->
  <!--        <button id="cancelButton">Annuler</button>-->
  <!--    </div>-->
  <!--    <div id="deleteEventModal">-->
  <!--        <h3>Evenement</h3>-->
  <!--        <p id="eventText"></p>-->
  <!--        <button id="deleteButton">Supprimer</button>-->
  <!--        <button id="closeButton">Fermer</button>-->
  <!--    </div>-->
  <!--    <div id="modalBackDrop"></div>-->
  <!--</section>-->
  <!--<section class="container__section--fourth">-->
  <!--</section>-->
</main>
<a href="?route=login">Administration</a>
<script type="text/javascript" src="main.js"></script>