<main class="container" id="index">
  <section class="container__section--first">
    <div class="section__first--masque">
      <h1>Belle Époque</h1>
      <p>Association de dance Country & Line</p>
    </div>
  </section>
  <section class="container__section--third">
    <h2>L'association</h2>
    <div class="section--presentation-container">
      <article class="card--presentation">
        <img src="./img/image7.jpg" alt="Image d'un bal country" 
        class="article-image">
      </article>
      <article class="card--presentation">
        <div class="presentation--details">
          <h3>Qui sommes nous?</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel, 
          aliquam, modi, laudantium quis velit sed nisi aliquid commodi itaque 
          sunt expedita ad architecto. Unde, possimus, iure, dolorum, officia ad
          nam minima et assumenda modi saepe laudantium pariatur totam quis quod.</p>
          <button class="button-4" role="button">
            <span class="text">
              <a href="/BelleEpoque/">En savoir plus</a> 
            </span>
          </button>
        </div>
        <div class="presentation--details">
          <h3>Envie de nous rejoindre?</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel, 
          aliquam, modi, laudantium quis velit sed nisi aliquid commodi itaque 
          sunt expedita ad architecto. Unde, possimus, iure, dolorum.</p>
          <button class="button-4" role="button">
            <span class="text">
              <a href="/BelleEpoque/">Nous rejoindre</a> 
            </span>
          </button>
        </div>
      </article>
    </div>
  </section>
  <section class="container__section--second">
    <h2>Derniers cours mis en ligne</h2>
    <div class="section__second--card-container">
      <?php 
        require './src/includes/_lastcours.phtml';
      ?>
    </div>
    <div class="section__second--all">
      <button class="button-4" role="button">
        <span class="text">
          <a href="/BelleEpoque/allcours">Parcourir tous les cours</a> 
        </span>
      </button>
    </div>
  </section>
</main>