<main class="container" id="index">
  <section class="section--first">
    <div class="first--masque">
      <h1>Belle Époque</h1>
      <p>Association de dance Country & Line</p>
    </div>
  </section>
  <section class="section--second">
    <h2>L'association</h2>
    <div class="section--article">
      <article class="article--details disable">
        <img src="./img/image11.jpg" alt="Image d'un bal country" 
          class="article--img">
      </article>
      <article class="article--details">
        <div class="article--content">
          <h3>Qui sommes nous?</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel, 
            aliquam, modi, laudantium quis velit sed nisi aliquid commodi itaque 
            sunt expedita ad architecto. Unde, possimus, iure, dolorum, officia ad
            nam minima et assumenda modi saepe laudantium pariatur totam quis quod.
          </p>
          <button class="button-4" role="button">
          <span class="text">
          <a href="/BelleEpoque/">En savoir plus</a> 
          </span>
          </button>
        </div>
        <div class="article--content">
          <h3>Envie de nous rejoindre?</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel, 
            aliquam, modi, laudantium quis velit sed nisi aliquid commodi itaque 
            sunt expedita ad architecto. Unde, possimus, iure, dolorum.
          </p>
          <nav class="page">
            <button class="button-4" role="button">
            <span class="text">
            <a href="/BelleEpoque/">Nous rejoindre</a> 
            </span>
            </button>
          </nav>
        </div>
      </article>
    </div>
  </section>
  <section class="section--third">
    <h2>Derniers cours mis en ligne</h2>
      <?php 
        require './src/includes/_lastcours.phtml';
      ?>
      <button class="button-4" role="button">
      <span class="text">
      <a href="/BelleEpoque/allcours">Parcourir tous les cours</a> 
      </span>
      </button>
  </section>
      <?php require './src/includes/_navsection.phtml'; ?>
</main>