<!doctype html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css" type="text/css" />
    <title>Belle-Epoque ~ </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cherry+Swash:wght@400;700&family=Montserrat&display=swap" rel="stylesheet">
  </head>
  <body>
    <header class="header">
      <div class="header__logo">
        <p class="logo">Belle Époque</p>
      </div>
      <div class="header__menu">
        <ul class="header__menu--list">
          <li class="header__menu--items">
            <a href="#">Accueil</a>
          </li>
          <li class="header__menu--items">
            <a href="#">Cours</a>
          </li>
          <li class="header__menu--items">
            <a href="#">Calendrier</a>
          </li>
          <li class="header__menu--items">
            <a href="#">A propos</a>
          </li>
        </ul>
      </div>
    </header>
    
      <?php 
        require './src/Templates/home_screen.phtml';
      ?>
    </main>
    <a href="?route=login">Administration</a>
    <script type="text/javascript" src="main.js"></script>
  </body>
</html>