<main class="container" id="aside">
  <section class="section--second">
    <h2>A propos</h2>
    <article class="section__article">
      <div class="cards__center">
        <h3>Mentions légales</h3>
          <p>ASSOCIATION COUNTRY BELLE EPOQUE, demeurant au 20 rue des roses, 53410 SAINT-OUEN-DES-TOITS, immatriculée au répertoire des entreprises et établissements de l'INSEE sous le numéro 811 469 857 00015, agissant en sa qualité d'Association déclarée.</p>
      </div>
    </article>
    <button class="button-4" role="button">
        <span class="text">
          <a href="javascript:history.go(-1)">Retour</a>
        </span>
      </button>
  </section>
  <?php require './src/includes/_aside.phtml'; ?>
</main>