<main class="container" id="singlecours">
  <section class="single-cours-container">
    <h2><?= $cours->getTitle();?></h2>
    <div class="section__second--card-container">
      <div class="cards">
        <div class="cards-center">
          <ul class="card-information-cour">
            <li class="description-cours-li"><span>Compte: </span>
            <span class="cours-li-result"><?= $cours->getCompte();?></span></li>
            <li class="description-cours-li"><span>Mur: </span>
            <span class="cours-li-result"><?= $cours->getMur();?></span></li>
            <li class="description-cours-li"><span>Niveau: </span>
            <span class="cours-li-result"><?= $cours->getNiveau();?></span></li>
            <li class="description-cours-li"><span>Chorégraphe: </span>
            <span class="cours-li-result"><?= $cours->getChoregraphe();?></span></li>
            <li class="description-cours-li"><span>Musique: </span>
            <span class="cours-li-result"><?= $cours->getMusique();?></span></li>
            <li class="description-cours-li">
            <span class="cours-li-result"><img src="../img/icons/file_pdf.svg"><a href="<?= $cours->getPdf();?>">
              Voir le pdf</a></span></li>
          </ul>
        </div>
      </div>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/<?= $cours->getLien(); ?>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <button class="button-4" role="button">
        <span class="text">
          <a href="javascript:history.go(-1)">Retour</a>
        </span>
      </button>
  </section>
  <?php require './src/includes/_aside.phtml'; ?>
</main>