<main class="container" id="singlecours">
  <section class="single-cours-container">
    <h2><?= $cours->getTitle();?></h2>
    <div class="section__second--card-container">
      <div class="cards">
        <div class="cards-top">
          <h3><?= $cours->getTitle();?></h3>
        </div>
        <div class="cards-center">
          <ul class="card-information-cour">
            <li class="description-cours-li">Compte: <?= $cours->getCompte();?></li>
            <li class="description-cours-li">Mur: <?= $cours->getMur();?></li>
            <li class="description-cours-li">Niveau: <?= $cours->getNiveau();?></li>
            <li class="description-cours-li">Chorégraphe: <?= $cours->getChoregraphe();?></li>
            <li class="description-cours-li">Musique: <?= $cours->getMusique();?></li>
          </ul>
        </div>
      </div>
    </div>
    <button class="button-4" role="button">
        <span class="text">
          <a href="javascript:history.go(-1)">Retour</a>
        </span>
      </button>
  </section>
  <?php require './src/includes/_aside.phtml'; ?>
</main>