<main class="container" id="dashboard">
  <section class="section--second">
      <form action="/BelleEpoque/admin/addcours" method="post" enctype="multipart/form-data">
        <fieldset>
          <legend>Ajouter un cours</legend>
          <div class="field">
            <label for="title">Titre</label>
            <div class="value">
              <input type="text" name="titre">
            </div>
          </div>
          <div class="field">
            <label for="compte">Compte</label>
            <div class="value">
              <input type="text" name="compte">
            </div>
          </div>
          <div class="field">
            <label for="mur">Mur</label>
            <div class="value">
              <input type="text" name="mur">
            </div>
          </div>
          <div class="field">
            <label for="niveau">Niveau</label>
            <select id="niveau" name="niveau">
              <option value="1">Débutant</option>
              <option value="2">Intermédiaire</option>
              <option value="3">Confirmé</option>
              <option value="4">Expert</option>
            </select>
          </div>
          <div class="field">
            <label for="choregraphe">Choregraphe</label>
            <div class="value">
              <input type="text" name="choregraphe">
            </div>
          </div>
          <div class="field">
            <label for="musique">Musique</label>
            <div class="value">
              <input type="text" name="musique">
            </div>
          </div>
          <div class="field">
            <label for="lien">Lien</label>
            <div class="value">
              <input type="text" name="lien">
            </div>
          </div>
          <div class="field">
            <label for="lien">pdf</label>
            <div class="value">
              <input type="text" name="pdf">
            </div>
          </div>
        </fieldset>
        <div class="toolbar">
          <button type="submit" class="button-4">Importer le cours</button>
        </div>
      </form>
  </section>
</main>