<main class="adm__container">
  <section class="adm__container__section--first">
    <div class="adm__section__first--masque">
      <form action="/BelleEpoque/admin/addcours" method="post" enctype="multipart/form-data">
        <fieldset>
          <legend>Ajouter un cours</legend>
          <div class="field">
            <label for="title">Titre</label>
            <div class="value">
              <input type="text" name="titre">
            </div>
          </div>
          <div class="field">
            <label for="compte">Compte</label>
            <div class="value">
              <input type="text" name="compte">
            </div>
          </div>
          <div class="field">
            <label for="mur">Mur</label>
            <div class="value">
              <input type="text" name="mur">
            </div>
          </div>
          <div class="field">
            <label for="niveau">Niveau</label>
            <div class="value">
              <input type="text" name="niveau">
            </div>
          </div>
          <div class="field">
            <label for="choregraphe">Choregraphe</label>
            <div class="value">
              <input type="text" name="choregraphe">
            </div>
          </div>
          <div class="field">
            <label for="musique">Musique</label>
            <div class="value">
              <input type="text" name="musique">
            </div>
          </div>
          <div class="field">
            <label for="lien">Lien</label>
            <div class="value">
              <input type="text" name="lien">
            </div>
          </div>
          <div class="field">
            <label for="lien">pdf</label>
            <div class="value">
              <input type="text" name="pdf">
            </div>
          </div>
          <!--<div class="field">-->
          <!--  <label for="musique">Importer le pdf</label>-->
          <!--  <div class="value">-->
          <!--    <input type="file" name="fileToUpload" id="fileToUpload">-->
          <!--  </div>-->
          <!--</div>-->
        </fieldset>
        <div class="toolbar">
          <button type="submit" class="button">Importer le cours</button>
        </div>
      </form>
    </div>
  </section>
</main>