<main class="container" id="dashboard">
	<section class="section--second">
		<h2>Tous les cours</h2>
		<?php
		include './src/includes/_admnavletter.phtml';
		?>
		<section class="section__cards">
			<?php
			foreach($allCours as $cours)
			{
			?>
				<article class="cards">
					<div class="cards-top">
						<h3><?= $cours['title'];?></h3>
					</div>
					<div class="cards-center">
						<ul class="description-cours-ul">
							<li class="description-cours-li">Compte: <?= $cours['compte'];?></li>
							<li class="description-cours-li">Mur: <?= $cours['mur'];?></li>
							<li class="description-cours-li">Niveau: <?= $cours['niveau'];?></li>
							<li class="description-cours-li">Chorégraphe: <?= $cours['choregraphe'];?></li>
							<li class="description-cours-li">Musique: <?= $cours['musique'];?></li>
						</ul>
					</div>
					<div class="cards-bottom">
						<button class="button-4">
							<a href="/BelleEpoque/admin/singlecours/<?= $cours['id'] ?>">Voir le cours</a>
						</button>
						<button class="button-4">
							<a href="/BelleEpoque/admin/editcours/<?= $cours['id'] ?>">Modifier le cours</a>
						</button>
						<button class="button-4">
							<a href="/BelleEpoque/admin/deletecours/<?= $cours['id'] ?>">Supprimer le cours</a>
						</button>
					</div>
				</article>
			<?php
			}
			?>
		</section>
	</section>
</main>