<main class="container" id="dashboard">
  <section class="section--second">
    <form action="/BelleEpoque/admin/galerie/<?= $images->getId(); ?>"
    method="post" enctype="multipart/form-data">
      <fieldset>
        <legend>Editer <?= $images->getTitle(); ?></legend>
        <div class="field">
          <label for="compte">Titre</label>
          <div class="value">
            <input type="hidden" name="id" value="<?= $images->getId(); ?>">
            <input type="text" name="title" value="<?= $images->getTitle(); ?>" id="title">
          </div>
        </div>
         <div class="field">
            <label for="image">Choisir une photo</label>
            <div class="value">
              <input type="file" accept="image/png, image/jpeg" name="image" value="<?= $images->getLien(); ?>">
            </div>
          </div>
      </fieldset>
      <div class="toolbar">
        
        <button type="submit" class="button-4" name="editphoto">Editer le cours</button>
      </div>
    </form>
  </section>
</main>