<main class="container" id="singlecours">
  <section class="container__section--second">
    <h2><?= $cours->getTitle();?></h2>
    <div class="section__second--card-container">
      <div class="cards">
        <div class="cards-top">
          <h3><?= $cours->getTitle();?></h3>
        </div>
        <div class="cards-center">
          <ul class="card-information-cour">
            <li class="description-cours-li">Compte: <?= $cours->getCompte();?></li>
            <li class="description-cours-li">Mur:<?= $cours->getMur();?></li>
            <li class="description-cours-li">Niveau: <?= $cours->getNiveau();?></li>
            <li class="description-cours-li">Chorégraphe: <?= $cours->getChoregraphe();?></li>
            <li class="description-cours-li">Musique: <?= $cours->getMusique();?></li>
          </ul>
        </div>
        <div class="cards-bottom">
          <button>
            <a href="/BelleEpoque/admin/editcours/<?= $cours->getId(); ?>">Modifier le cours</a>
          </button>
          <button>
            <a href="/BelleEpoque/admin/deletecours/<?= $cours->getId(); ?>">Supprimer le cours</a>
          </button>
      </div>
    </div>       
  </section>
</main>